authLogin:
  handler: auth/index.login
  events:
    - http:
        path: /v1/auth/login
        method: POST
        cors: true

authLogout:
  handler: auth/index.logout
  events:
    - http:
        path: /v1/auth/logout
        method: POST
        cors: true

authRegister:
  handler: auth/index.register
  events:
    - http:
        path: /v1/auth/register
        method: POST
        cors: true

authChangePassword:
  handler: auth/index.changePassword
  events:
    - http:
        path: /v1/auth/change-password
        method: POST
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer

authVerify:
  handler: auth/index.verify
  events:
    - http:
        path: /v1/auth/verify
        method: GET
        cors: true

authResendVerificationCode:
  handler: auth/index.resendVerificationCode
  events:
    - http:
        path: /v1/auth/resend-verification-code
        method: POST
        cors: true

authForgotPassword:
  handler: auth/index.forgotPassword
  events:
    - http:
        path: /v1/auth/forgot-password
        method: POST
        cors: true

authConfirmForgotPassword:
  handler: auth/index.confirmForgotPassword
  events:
    - http:
        path: /v1/auth/confirm-forgot-password
        method: POST
        cors: true

authRefreshToken:
  handler: auth/refreshToken.handler
  events:
    - http:
        path: /v1/auth/refresh-token
        method: POST
        cors: true

customMessage:
  handler: auth/index.customMessage
  dependsOn:
    - CognitoUserPool
  events:
    - cognitoUserPool:
        existing: true
        pool: safe-zone-auth-pool-${opt:stage, 'dev'}
        trigger: CustomMessage

authChangePhoneNumber:
  handler: auth/index.changePhoneNumber
  events:
    - http:
        path: /v1/auth/change-phone-number
        method: POST
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer

authRegisterByAdmin:
  handler: auth/index.registerByAdmin
  events:
    - http:
        path: /v1/auth/register-by-admin
        method: POST
        cors: true
