ordersDetailsGet:
  handler: orders/getDetails.handler
  events:
    - http:
        path: /v1/orders/{orderId}
        method: GET
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer
